### ISSUE TITLE
Control flow temperature target from HA

### ISSUE THREAD

**Issue by limkinZero** [rbroker/ecodan-ha-local#17]
Hi @rbroker ,

I push a new PR #16  to manage the Z1 flow temperature target from home assistant.

![image](https://github.com/rbroker/ecodan-ha-local/assets/14091407/7e8b9458-66c1-497a-8dc0-a686f2f143c9)

**Comment by rbroker** [comment]
Thank you very much! I've merged the changes as they look good to me, and pushed an additional fix for the mistakes I made in the std::lock_guard calls.
