### ISSUE TITLE
Always switch back to "Heat Target Temperature"

### ISSUE THREAD

**Issue by dinkel1975** [rbroker/ecodan-ha-local#38]
Hi,
I don't get it to work. 
No matter which heating mode I set, after a short time it jumps back to "Heat Target Temperature". Can you help me?
Best regards
Michael

**Comment by rbroker** [comment]
Hi,

Usually switching back means the command home assistant tried to send hasn't worked correctly, so the state is set back the next time the sensor status is updated.

Is it possible to see if there's anything suspicious in the log messages on the diagnostics tab of the ESP32 web UI when you try and switch the mode?

Thanks,
Richard

**Comment by dinkel1975** [comment]
hi,

In the meantime I have tried the Image from here https://github.com/tobias-93/esphome-ecodan-heatpump
With this Firmware mode switching is OK. 

Ciao 
Michael

**Comment by rbroker** [comment]
Ok! No problem
